version: "2.29"
services:
    api:
        build:
            context: .
            target: build
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 8000:8000
        command: npm run dev
