version: "3.9"
services:
    mongo_db:
        container_name: db_container
        image: mongo:latest
        restart: always
        volumes:
            - mongo_db:/data/db
    api:
        build: .
        ports:
            - 4000:3000
        volumes:
            - ./:/app
            - /app/node_modules
        environment: PORT=3000
            NODE_ENV=development
            MONGO_URL=mongodb+srv://myohsat:taskMaster123@cluster0.aydye.mongodb.net/taskmaster
            JWT_SECRET=8b3e5c4a9d12f3e7a1b0c6d4f8e5a7b2c0d9e1f8a7b5c6d9e0f2b1a8c3e4f5d6g7
            JWT_TTL=1h
            REFRESH_TOKEN_SECRET=d9e0b4c6e9d40f4e8f0e743a2b8b9f1d21f0a9e8b7f4c2a1d9d8e0a0f8c4b5e0f
            REFRESH_TOKEN_TTL=30d
            PINO_LOG_LEVEL=info
        command: npm run dev
