name: CI-CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: setup node
              uses: actions/setup-node@master
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm run test

            - name: Build Docker image
              run: docker build -t task-master:latest .
            - name: List Docker images
              run: docker images

    deploy_to_docker_hub:
        runs-on: ubuntu-latest
        needs: [build]
        if: github.ref == 'refs/heads/main'

        steps:
            - name: checkout repo
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Tag Docker image
              run: docker tag task-master:latest ${{ secrets.DOCKERHUB_USERNAME }}/task-master:latest

            - name: Push Docker image to Docker Hub
              run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/task-master:latest
