name: CI-CD

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build_test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: setup node
              uses: actions/setup-node@master
              with:
                  node-version: 18.x

            - name: Install dependencies
              run: |
                  npm ci

            - name: build
              run: |
                  npm run build
                  npm run test
    push_to_Docker_Hub:
        runs-on: ubuntu-latest
        needs: [build_test]

        steps:
            - name: checkout repo
              uses: actions/checkout@v2

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: ./
                  file: ./Dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/task-master-api:latest

            - name: Run the image in a container
              uses: addnab/docker-run-action@v3
              with:
                  image: ${{ secrets.DOCKERHUB_USERNAME }}/task-master-api:latest
                  run: |
                      echo "runing the docker image"
                      echo "Testing the nodejs  app endpoints"
                      echo ${{ steps.docker_build.outputs.digest }}
